#!/usr/bin/env python
import ldap
import ldap.modlist as modlist

import sys

import cshldap
#Print Usage if no arguments provided
shell = ''

def changeShell(shell):
    etcshells = open('/etc/shells', 'r')
    line = etcshells.readline()
    while line != '':
        validshell = line.strip()
        if shell == validshell:
            print "Changing shell to %s" % (validshell)
            ldap = cshldap.CSHLDAP('ldap://ldap.csh.rit.edu')
            usernameldap = ldap.conn.whoami_s()
            index = usernameldap.find(',')
            username = usernameldap[len('dn:uid='): index]
            dn="uid=%s,ou=Users,dc=csh,dc=rit,dc=edu" % (username)
            old = {'loginShell': '*'}
            new = {'loginShell': '%s' % (validshell)}
            ldif = modlist.modifyModlist(old,new)
            ldap.conn.modify_s(dn,ldif)
            ldap.conn.unbind_s()
            print "Shell successfully changed, typically it takes a while for the changes to propagate to all our machines"
            exit()
        else:
            line = etcshells.readline()
    print("You didn't put in a valid shell. Try again by reruning chsh.")
if len(sys.argv) < 2:
  print("Usage: chsh shell")
  print("You appear to be changing your shell.")
  shell = raw_input("Type in the shell you want. Make sure you use /bin/ prefixed before it.\n")
  changeShell(shell)
else:
    shell = sys.argv[1]
    changeShell(shell)

